#!/bin/bash

################################################################################################################
#                                                                                                              #
# MACTOOL - ARCHNON LINUX TOOL FOR MANAGING MAC ADDRESS OF INTERFACES ANONYMOUS DNS.                           #
# CODED BY: archnon@protonmail.com, btw.                                                                       #
#                                                                                                              #
################################################################################################################

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"


if ! (command -v sudo >/dev/null 2>&1 && command -v macchanger >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1); then

       pkgs=(sudo macchanger figlet)

       if [[ $(command -v apt) ]]; then
                if ! apt install -y ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v pacman) ]]; then
                if ! pacman -Sy --noconfirm --needed --overwrite "*" ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v dnf) ]]; then
                if ! dnf install -y --allowerasing ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v yum) ]]; then
                if ! yum install -y ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v xbps-install) ]]; then
                if ! xbps-install -Sy -f -y "*" ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v zypper) ]]; then
                if ! zypper install ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v apk) ]]; then
                if ! apk add --no-cache ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        elif [[ $(command -v emerge) ]]; then
                if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
                fi
        else
                echo -e "\n${RED}[${NC}-${RED}] Unsuported package manager, install: ${ORANGE}'${pkgs[@]}'${NC}"
                exit 1
        fi
fi

# Banner

echo -e "${GREEN}" && figlet mactool
echo -n -e "${BLUE}v2.0.0 ${LB}-->${GREEN} MAC Address util${NC}"
echo -e "\n"
echo -e "${ORANGE}[${BLUE}*${ORANGE}] ${YELLOW}Coded By: ${ORANGE}archnon@protonmail.com ${NC}"

usage(){
echo -e "\n${ORANGE}[${YELLOW}*${ORANGE}]${GREEN} usage: ${P}$0 ${NC}<${GREEN}COMMAND${NC}> ${NC}<${GREEN}OPTIONS${NC}>${NC}"
echo -e "\n${BLUE}[${ORANGE}1${BLUE}] ${ORANGE}-c${BLUE}|${ORANGE}--change-mac${NC}: ${NC}${GREEN}Change MAC of device${NC}"
echo -e "\n${BLUE}[${ORANGE}2${BLUE}] ${ORANGE}-e${BLUE}|${ORANGE}--enable-boot${NC}: ${GREEN}Enable MAC changing on boot${NC}"
echo -e "\n${BLUE}[${ORANGE}3${BLUE}] ${ORANGE}-d${BLUE}|${ORANGE}--disable-boot${NC}: ${RED}Disable ${GREEN}MAC changing on boot${NC}"
echo -e "\n${BLUE}[${ORANGE}4${BLUE}] ${ORANGE}-b${BLUE}|${ORANGE}--in-background-change${NC} <${P}arg${NC}>: ${GREEN}Daemonize MAC changing of device${NC}"
echo -e "\n${BLUE}[${ORANGE}5${BLUE}] ${ORANGE}-r${BLUE}|${ORANGE}--restore-mac: ${GREEN}Restore Device's MAC${NC}"
echo -e "\n${BLUE}[${ORANGE}6${BLUE}] ${ORANGE}-l${BLUE}|${ORANGE}--list-available-devices${NC}: ${GREEN}Show Available Devices${NC}"
}

change(){
ip link set $device down >/dev/null 2>&1

macchanger -r -b $device >/dev/null 2>&1

ip link set $device up >/dev/null 2>&1
}

restore(){
ip link set $device down >/dev/null 2>&1

macchanger -p $device >/dev/null 2>&1

ip link set $device up >/dev/null 2>&1
}

createsv(){
if [ ! -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/mactool.service

echo -e "\n[Unit]\nDescription=MacTool Service\n[Service]\nType=forking\nExecStart=mactool change $device\nRemainAfterExit=yes\nUser=root\n[Install]\nWantedBy=multi-user.target" >> /etc/systemd/system/mactool.service

fi

if [ ! -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/mactool/
    touch /etc/sv/mactool/run

    echo -e "#!/bin/sh\nexec mactool change $device" >> /etc/sv/mactool/run
    chmod +x /etc/sv/mactool/run
fi

if [ ! -f /etc/init.d/mactool ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/mactool

echo "#!/sbin/openrc-run\nname=MacTool service\ncommand="mactool"\ncommand_args="change $device"\ncommand_background=true\npidfile="/run/${RC_SVCNAME}.pid"\ndepend() {\n   need net\n}" >> /etc/init.d/mactool

   chmod +x /etc/init.d/mactool >/dev/null 2>&1
fi
}

enable(){

if [ -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled mactool >/dev/null 2>&1; then
       echo -e "\n${P}[${NC}*${P}]${NC} MacTool is enabled${NC}"
    else
        systemctl enable mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enabled${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
    fi
fi

if [ -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then

        if [ -d /run/runit/service ]; then
            RSDIR=/run/runit/service
        elif [ -d /etc/service ]; then
              RSDIR=/etc/service
        elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
        fi

      if ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
            echo -e "\n${P}[${NC}*${P}]${NC} MacTool is enabled${NC}"
      else
           ln -s /etc/sv/mactool $RSDIR >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enabled${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
      fi
fi

if [ -f /etc/init.d/mactool ] && command -v rc-update >/dev/null 2>&1; then

      if sudo rc-update | grep -iE "mactool" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${GREEN} MacTool is enabled${NC}"
      else
           sudo rc-update add mactool default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
      fi
fi
}

disable(){
if [ -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled mactool >/dev/null 2>&1; then
        echo -e "\n${RED}[${NC}+${RED}]${NC} MacTool is disabled${NC}"
        exit 0
    else

    systemctl disable mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
    exit 1
    fi
fi

if [ -f /etc/sv/mactool/run ] && command -v runit  >/dev/null 2>&1; then

      if [ -d /run/runit/service ]; then
          RSDIR=/run/runit/service

      elif [ -d /etc/service ]; then
              RSDIR=/etc/service

      elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
      fi

      if ! ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} MacTool is already disabled${NC}"
           exit 0
      else

      rm -rf $RSDIR/mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
      exit 1
      fi
fi

if [ -f /etc/init.d/mactool ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "mactool" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} MacTool is already disabled${NC}"
           exit 0
      else

      rc-update del mactool default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
      exit 1
      fi
fi
}

dlist(){
echo -e "\n${BLUE}[${GREEN}*${BLUE}]${GREEN} Daemon's Active PIDs${NC}: ${ORANGE}"
pgrep -a mactd && echo -e "${NC}"
echo -e "\n${RED}[${NC}-${RED}]${NC} Kill them by running: ${RED}sudo pkill -9 mactd${NC}"
}

while [ $# -gt 0 ]; do
        case $1 in

        -c|-change-mac|--change-mac)
        mode=1
        device=$2

        if [ $EUID -ne 0 ]; then
            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
            exit 1
        fi

        if [ -z $device ]; then
            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
            exit 1
        fi

        if ! ip a | grep "$device" >/dev/null 2>&1; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
                exit 1
        fi

        change && echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} $device's MAC was changed${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not change MAC Addr of: ${ORANGE}'$device'${NC}"
        echo -e "${ORANGE}"
        macchanger -s $device && echo -e "\n${NC}"
        exit 1

        shift
        break


        ;;

        -e|-enable-boot|--enable-boot)
        mode=2
        device=$2

        if [ $EUID -ne 0 ]; then
            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
            exit 1
        fi

        if [ -z $device ]; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
                exit 1
        fi

        if ! ip a | grep "$device" >/dev/null 2>&1; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
                exit 1
        fi

        createsv

        enable

        exit 0

        shift
        break

        ;;

        -d|-disable-boot|--disable-boot)
        mode=3
        device=$3

        if [ $EUID -ne 0 ]; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
                exit 1
        fi

        createsv

        disable

        exit 0

        shift
        break

        ;;

        -b|-in-background-change|--in-background-change)
        mode=4
        i=$2
        device=$3

        if [ $EUID -ne 0 ]; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
                exit 1
        fi

        if pgrep -a mactd >/dev/null 2>&1; then
                dlist
        fi

        if [ -z $i ]; then
                echo -e "\n${RED}[${NC}-${RED}] Missing interval(${ORANGE}secs${RED})${NC}"
                exit 1
        fi

        if [ -z $device ]; then
                echo -e "\n${RED}[${NC}-${RED}] Missing device name${NC}"
                exit 1
        fi

        if ! ip a | grep "$device" >/dev/null 2>&1; then
                dlist
                echo -e "\n${RED}[${NC}-${RED}] No such device ${ORANGE}'$device'${NC}"
                exit 1
        fi

        if ! command -v mactd >> /dev/null 2>&1; then
                echo -e "\n${RED}[${NC}-${RED}] Missing Daemon script ${ORANGE}'mactd'${NC}"
                exit 1
        else
                mactd $i $device && echo -e "\n${ORANGE}[${BLUE}notice${ORANGE}]${GREEN} New Daemon Launched !${NC}" || echo -e "\n${RED}[${NC}-${RED}] Could not launch daemon${NC}"
                exit 0
        fi

        shift
        break

        ;;

        -r|-restore-mac|--restore-mac)
        mode=5
        device=$2

        if [ $EUID -ne 0 ]; then
                echo -e "\n${RED}[${NC}-${RED}] Run as root${NC}"
                exit 1
        fi


        if [ -z $device ]; then
                usage
                echo -e "\n${RED}[${NC}-${RED}] Missing device name${NC}"
                exit 1
        fi


        if ! ip a | grep "$device" >/dev/null 2>&1; then
                echo -e "\n${RED}[${NC}-${RED}] No such device ${ORANGE}'$device'${NC}"
                exit 1
        fi

        restore && echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} $device's MAC was restored${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}] Could not restore MAC${NC}"
        macchanger -s $device && echo -e "\n${NC}"
        exit 0

        shift
        break

        ;;

        -l|-list-available-devices|--list-available-devices)
        mode=6

        echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Available Devices${NC}:" && ip link || echo -e "\n${RED}[${NC}-${RED}] Could not show devices${NC}"

        exit 0
        shift
        break

        ;;

        --*|-*|*)
        mode=6

        usage
        exit 1

        shift
        break

        ;;
esac
done

if [ -z $mode ]; then
        usage
        exit 1
fi
