#!/bin/bash

################################################################################################################
#                                                                                                              #
# NEPTUNE_RESOLV - ARCHNON LINUX TOOL FOR RESOLVING AND CONFIGURING ANONYMOUS DNS.                             #
# CODED BY: archnon@protonmail.com, btw.                                                                       #
#                                                                                                              #
################################################################################################################

##### Colors #####

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

##### Default Socks5 Address #####
ADDR=127.0.0.1
PORT=9150

usage(){
echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} usage: ${P}neptuner ${NC}<${LB}option${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}1${BLUE}]${ORANGE} -u${BLUE}|${ORANGE}--url ${NC}<${P}url${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}2${BLUE}]${ORANGE} -a${BLUE}|${ORANGE}--resolv-with-address ${NC}<${P}addr${NC}> <${P}url${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}3${BLUE}]${ORANGE} -s${BLUE}|${ORANGE}--set-dns-address ${NC}<${P}addr${NC}>${NC}"
}

logos=figlet

if ! command -v $logos >/dev/null 2>&1; then
        if [[ $(command -v apt) ]]; then
                if ! apt install -y $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v pacman) ]]; then
                if ! pacman -Sy --noconfirm --needed --overwrite "*" $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v dnf) ]]; then
                if ! dnf install -y --allowerasing $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v yum) ]]; then
                if ! yum install -y $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v xbps-install) ]]; then
                if ! xbps-install -Sy -f -y "*" $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v zypper) ]]; then
                if ! zypper install $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v apk) ]]; then
                if ! apk add --no-cache $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        elif [[ $(command -v emerge) ]]; then
                if ! emerge -v --oneshot --keep-going $logos; then
                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}$logos${NC}"
                exit 1
                fi
        else
                echo -e "\n${RED}[${NC}-${RED}] Unsuported package manager, install: ${ORANGE}'$logos'${NC}"
                exit 1
        fi
fi


echo -e "${P}" && figlet neptuner
echo -n -e "${ORANGE}v2.0.0 ${LB}-->${P} Anonymous DNS Util${NC}"
echo -e "\n"
echo -e "${ORANGE}[${YELLOW}*${ORANGE}] ${GREEN}Coded By: ${ORANGE}archnon@protonmail.com${NC}"

while [ $# -gt 0 ]; do
        case $1 in
        -u|-url|--url)
        mode=1
        url=$2

        if [ -z $url ]; then
            echo -e "\n${RED}[${NC}-${RED}] Missing an url${NC}"
            echo -e "\n${ORANGE}[${YELLOW}!${ORANGE}]${NC} usage: ${LB}$0 ${P}--url ${YELLOW}<${NC}url${YELLOW}>${NC}"
            exit 1
        else
            SOCKS5=$ADDR:$PORT
            echo -e "\n${LB}[${YELLOW}*${LB}]${BLUE} Default Address: ${ORANGE}$ADDR${GREEN}:${YELLOW}$PORT${NC}"
            curl -s --socks5-hostname $SOCKS5 "$url" && echo -e "${NC}" || echo -e "\n${RED}[${NC}err${RED}] Could not resolv: ${YELLOW}"$url"${NC}"
            exit 0
        fi

        shift
        break

        ;;

        -a|-resolv-with-address|--resolv-with-address)
        mode=2
        NEW_ADDR=$2
        url=$3

        if [[ -z $NEW_ADDR || -z $url ]]; then
            echo -e "\n${RED}[${NC}-${RED}] Missing url or address${NC}"
            echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${NC} usage: ${LB}$0 ${P}--resolv-with-address ${NC}<${BLUE}addr${NC}> <${BLUE}url${NC}>${NC}"
            exit 1
        else
           SOCKS5="$NEW_ADDR"
           curl --socks5-hostname $SOCKS5 "$url" && echo -e "${NC}" || echo -e "\n${RED}[${NC}-${RED}] Could not resolv: ${YELLOW}"$url"${NC}"
           exit 0
        fi

        shift
        break

        ;;
	
	-s|-set-dns-address|--set-dns-address)
	mode=3
	addr=$2

	if ! [ -f /etc/resolv.conf ]; then
		touch /etc/resolv.conf >/dev/null 2>&1
	fi

	if [ -z $addr ]; then
		echo -e "\n${RED}[${NC}err${RED}] ${RED}Missing the address to set${NC}"
		echo -e "\n${RED}[${ORANGE}warn${RED}]${NC} usage: ${GREEN}$0 ${LB}--set-dns-address ${NC}<${P}addr${NC}>"
		exit 1
	else

	chattr -i /etc/resolv.conf >/dev/null 2>&1
	rm /etc/resolv.conf >/dev/null 2>&1
	touch /etc/resolv.conf >/dev/null 2>&1

	echo "nameserver $addr" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} New dns address: ${ORANGE}$addr${NC}" || echo -e "\n${RED}[${NC}err${RED}] Could not set dns address${NC}"
	exit 0

	fi

	shift
	break
	;;

    -h|--help|-help|help)
    mode=4

    usage
    exit 1

    shift
    break

    ;;

    --*|-*|*)
    mode=4

    echo -e "\n${RED}[${NC}-${RED}] invalid option: ${YELLOW}'$1'${NC}"
    echo -e "\n${ORANGE}[${YELLOW}warn${ORANGE}]${NC} Try: ${LB}'$0 --help'${NC}"

    shift
    break
    exit 1

    ;;

esac
done

if [ -z "$mode" ]; then
    usage
    exit 1
fi
