#!/bin/bash

##################################################################################################################################
# NEPTUNE - bash based privacy tool.                                                                                             #
# Based in: bash.                                                                                                                #
# Requires: netcat-openbsd curl tor nftables procps networkmanager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd #
# Version: 3.0.12.                                                                                                               #
# Developer is: archnon@protonmail.com, btw.                                                                                     #
##################################################################################################################################

# <-- colors -->

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[1;36m"

WHITE="\e[1;37m"

NC="\e[0m"

# <-- Dependencies --> #
# Always dynamic #

if ! (command -v nc >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v nft >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1 && command -v chattr >/dev/null 2>&1 && command -v i2pd >/dev/null 2>&1); then

       if [[ $(command -v apt) ]]; then

           pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

           if ! apt install "${pkgs[@]}" -y; then
                  echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                  exit 1
               fi
               wait

        elif [[ $(command -v pacman) ]]; then

              pkgs=( openbsd-netcat curl tor nftables procps-ng networkmanager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! pacman -Syy "${pkgs[@]}" --needed --noconfirm --overwrite "*"; then
                        echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                    exit 1
                 fi
                 wait

        elif [[ $(command -v dnf) ]]; then

              pkgs=( epel-release nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! dnf -y install --allowerasing "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v yum) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! yum -y install "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v zypper) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! zypper install "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v apk) ]]; then

              pkgs=( netcat-openbsd curl tor nftables procps networkmanager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! apk add --no-cache "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v xbps-install) ]]; then

              pkgs=( openbsd-netcat curl tor iproute2 coreutils util-linux bash nftables sudo procps-ng NetworkManager figlet e2fsprogs i2pd)

              if ! xbps-install -Sy -f -y "*" "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait
        elif [[ $(command -v emerge) ]]; then

              pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
                    echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                    exit 1
              fi
              wait
        else
              pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)
              echo -e "${RED}[${NC}err${RED}]${WHITE} Missing dependencies !!${NC}"
              echo -e "${RED}[${NC}err${RED}]${WHITE} Not common: ${RED}unsuported pkg manager${LB}, please, install: ${BLUE}(${LB}${pkgs[@]}${BLUE})${NC}"
              exit 1
        fi
fi

# <-- Banner --> #
# Here, so it checks dependencies first #

echo -e "${LB}" && figlet neptune
echo -n -e "${BLUE}[*]${ORANGE} Portable Bash Anonymation Tool${NC}"
echo -e "\n"
echo -e "${BLUE}[${GREEN}notice${BLUE}]${WHITE} Developed by: ${LB}archnon${P}@protonmail.com${NC}"

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/neptune.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/neptune.service
    cat << 'EOT' > /etc/systemd/system/neptune.service
[Unit]
Description=neptune
[Service]
Type=forking
ExecStart=/usr/local/bin/neptune start
RemainAfterExit=yes
User=root
[Install]
WantedBy=multi-user.target
EOT
fi

if [ ! -f /etc/sv/neptune/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/neptune/
    touch /etc/sv/neptune/run
    cat << 'EOT' > /etc/sv/neptune/run
#!/bin/sh
exec neptune start
EOT
    chmod +x /etc/sv/neptune/run
fi

if [ ! -f /etc/init.d/neptune ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/neptune
    cat << 'EOT' > /etc/init.d/neptune
#!/sbin/openrc-run
name=neptune
command="neptune"
command_args="start"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
depend() {
   need net
}
EOT
   chmod +x /etc/init.d/neptune >/dev/null 2>&1
fi


# <-- Address To Bind -->
# Default: 127.0.0.1(loopback/lo/localhost) #
# There's no place like 127.0.0.1.. #

IFNAME=lo
ADDR=127.0.0.1

# <-- Tor Ports --> #
# Tor is not an http proxy btw #
# Default order: 6969, 5353, 9150, 9151, 8181 #

TRANS=6969
DNS=5353
SOCKS=9150
CONTROL=9151
HTTP=8181 

# <-- Configuration Files --> #
# Always nftables instead of old iptables #
# Default order: /etc/tor/torrc, /etc/neptune_rules.nft #

TORRC=/etc/tor/torrc
FWFILE=/etc/neptune_rules.nft

# <-- Script Functions --> #
# Here logic becomes crazy #

# Torrc Check -->
torrc(){
if ! $(tor --verify-config >/dev/null 2>&1); then
	echo -e "\n${RED}[${WHITE}err${RED}] Invalid Torrc${WHITE}, Try ${ORANGE}'neptunec reset'${NC}"
	exit 1
fi
}
# <--

# Help page -->
help(){
	echo -e "\n${RED}[${ORANGE}warn${RED}]${YELLOW} usage: ${LB}neptune ${YELLOW}<${GREEN}option${YELLOW}>${NC}"
	echo -e "\n${ORANGE}[${WHITE}1${ORANGE}] ${LB}start: ${GREEN}Start ${WHITE}script${NC}"
	echo -e "\n${ORANGE}[${WHITE}2${ORANGE}] ${LB}stop: ${RED}Stop ${WHITE}script${NC}"
	echo -e "\n${ORANGE}[${WHITE}3${ORANGE}] ${LB}restart: ${YELLOW}Restart ${WHITE}script${NC}"
	echo -e "\n${ORANGE}[${WHITE}4${ORANGE}] ${LB}enable: ${GREEN}Enable ${ORANGE}script on boot${NC}"
	echo -e "\n${ORANGE}[${WHITE}5${ORANGE}] ${LB}disable: ${RED}Disable ${ORANGE}script on boot${NC}"
	echo -e "\n${ORANGE}[${WHITE}6${ORANGE}] ${LB}myip: ${BLUE}Show ${WHITE}your IP${NC}"
	echo -e "\n${ORANGE}[${WHITE}7${ORANGE}] ${LB}changeid: ${ORANGE}Change ${WHITE}your IP${NC}"
	exit 1
}
# <--

# Check IP -->
myip(){

# Default API: 'ip-api.com?fields=query,asname,org,country,region,continent,proxy,mobile,status'
# <- I recommend to get clear info ->

check_ip='ip-api.com?fields=query,asname,org,country,region,continent,proxy,mobile,status'

if pgrep -x tor >/dev/null 2>&1; then
	
	if ! curl --socks5-hostname $ADDR:$SOCKS $check_ip -w "\n" -s -m 5; then
		echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not check IP (timeout)${NC}"
		exit 1
	else
		exit 0
	fi
else
	if ! curl $check_ip -w "\n" -s -m 5; then
		echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not check IP (timeout)${NC}"
		exit 1
	else
		exit 0
	fi
fi

}
# <--

start(){

# Goodbye SELinux ! #

sudo setenforce 0 >/dev/null 2>&1
sudo semanage permissive -a unconfined_t >/dev/null 2>&1

# Ensuring Kernel modules before launching nft commands #

modprobe nft_nat >/dev/null 2>&1
modprobe nft_chain_nat >/dev/null 2>&1
modprobe nf_nat >/dev/null 2>&1

# Enforcing neptune's firewall rules here #

chattr -i $FWFILE >/dev/null 2>&1

rm $FWFILE >/dev/null 2>&1
touch $FWFILE >/dev/null 2>&1

sudo nft flush ruleset >/dev/null 2>&1

cat << EOT > $FWFILE
table ip6 filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                meta l4proto ipv6-icmp icmpv6 type echo-request counter packets 100 bytes 100 drop
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
        }
}
table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                iifname "$IFNAME" counter packets 100 bytes 100 accept
                ct state related,established counter packets 100 bytes 100 accept
                iifname "$IFNAME" ip protocol icmp icmp type echo-request ct state related,established counter packets 100 bytes 100 accept
                ip protocol icmp icmp type echo-request counter packets 100 bytes 100 drop
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
                oifname "$IFNAME" counter packets 100 bytes 100 accept
                ct state new,related,established counter packets 100 bytes 100 accept
                oifname "$IFNAME" ip protocol icmp icmp type echo-request ct state new,related,established counter packets 100 bytes 100 accept
                ip protocol icmp icmp type echo-request counter packets 100 bytes 100 drop
                skuid $TOR_USER counter packets 100 bytes 100 accept
                ip daddr $ADDR udp dport $DNS counter packets 100 bytes 100 accept
                ip daddr $ADDR tcp dport $TRANS counter packets 100 bytes 100 accept
                ip daddr $ADDR tcp dport $HTTP counter packets 100 bytes 100 accept
                counter packets 100 bytes 100 reject
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }
}
table ip nat {
        chain OUTPUT {
                type nat hook output priority dstnat; policy accept;
                ip daddr $ADDR udp dport 53 counter packets 100 bytes 100 redirect to :$DNS
                ip daddr $ADDR tcp dport 53 counter packets 100 bytes 100 redirect to :$DNS
                skuid $TOR_USER counter packets 100 bytes 100 return
                ip daddr 127.0.0.0/8 counter packets 100 bytes 100 return
                ip daddr 192.168.0.0/16 counter packets 100 bytes 100 return
                ip daddr 10.0.0.0/8 counter packets 100 bytes 100 return
                ip daddr 172.16.0.0/12 counter packets 100 bytes 100 return
                ip daddr 169.254.0.0/16 counter packets 100 bytes 100 return
                ip daddr 255.255.255.255 counter packets 100 bytes 100 return
                ip daddr 224.0.0.0/4 counter packets 100 bytes 100 return
		udp dport 53 counter packets 100 bytes 100 redirect to :$DNS
                tcp dport 53 counter packets 100 bytes 100 redirect to :$DNS
                tcp flags & (fin | syn | rst | ack) == syn counter packets 100 bytes 100 redirect to :$TRANS
                }
}
EOT

######## SSH Optional, delete if not needed ##########

SSH=22

sudo iptables -I INPUT -p tcp --dport $SSH -j ACCEPT >/dev/null 2>&1
sudo iptables -I OUTPUT -p tcp --dport $$SSH -j ACCEPT >/dev/null 2>&1

chattr +i $FWFILE >/dev/null 2>&1

nft -f $FWFILE >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Firewall Applied${NC}" || echo -e "\n${RED}[${NC}err${RED}] ${NC}Could not apply Firewall${NC}"

   sleep 1

   # Say goodbye to old PIDs and welcome to securest transparent proxy experience (i love my localhost) #

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "# <-- From neptune for sys global DNS -->#\nnameserver $ADDR" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} DNS is now: ${ORANGE}$ADDR${GREEN}${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not modify DNS file${NC}"

   sleep 1

   chmod 644 /etc/resolv.conf >/dev/null 2>&1
   chattr +i /etc/resolv.conf >/dev/null 2>&1

   while ! pgrep -x NetworkManager >/dev/null 2>&1; do
      NetworkManager >/dev/null 2>&1 && continue || break
   done && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Network was fixed${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not fix Network${NC}"

   	sleep 1

	tor --User $TOR_USER --RunAsDaemon 1 --DataDirectory /var/lib/tor -f $TORRC >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}was started${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not start Tor${NC}"
	i2pd --daemon >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${ORANGE} I2P was started${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not start i2pd${NC}"

   sleep 1

   	sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
	sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1
	sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1
	sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1
	sysctl --system >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} IPv6 was disabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not disable IPv6${NC}"

	sleep 1
	
   # Proxy PID simple check to confirm everything works #

   if pgrep -x tor >/dev/null 2>&1 && pgrep -a i2pd >/dev/null 2>&1; then

        sleep 1

        echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} neptune has been started${NC}"

   else
        sleep 1

	echo -e "${RED}[${NC}err${RED}]${NC} Could not start neptune correctly${NC}"
        exit 1
   fi
}

# Apply Default Torrc if user have not used neptunec to apply a custom one #

config(){

# here the check #
	
if ! cat $TORRC | grep -IE "NOT TOUCH, THIS FILE IS CUSTOM LOAD" >/dev/null 2>&1; then

   chattr -i $TORRC >/dev/null 2>&1

   rm $TORRC >/dev/null 2>&1
   touch $TORRC >/dev/null 2>&1

# default template #

   cat << EOT > $TORRC
# <--- Generated by neptune ---> #
# File locked by chattr +i, unlock: sudo chattr -i $TORRC

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort $ADDR:$TRANS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort $ADDR:$DNS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort $ADDR:$SOCKS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ControlPort $ADDR:$CONTROL
HTTPTunnelPort $ADDR:$HTTP
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 60
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1
AvoidDiskWrites 1
EnforceDistinctSubnets 1
HardwareAccel 1

EOT

chattr +i $TORRC >/dev/null 2>&1

fi

# Tor user detection(for firewall rules) #

   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}user: ${P}$TOR_USER${NC}"

   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}user: ${P}$TOR_USER${NC}"

   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}user: ${P}$TOR_USER${NC}"

   else

# Sorry, but i cant start without this user :( #

        echo -e "\n${RED}[${NC}err${RED}]${NC} Could not detect a Tor user${NC}"
        exit 1
   fi
	
# File permissions(owned by system's tor user) #

   chown -R $TOR_USER:$TOR_USER $TORRC >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   chmod 700 /var/lib/tor >/dev/null 2>&1

   sleep 1
	
# Once everything is done, we call start #

   start
}


stop(){

# Check if tor is even running #

if pgrep -x tor >/dev/null 2>&1; then
	
   sleep 1

# Everything starts being normal from here #

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Tor and Network were stopped${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not stop Tor or Network${NC}"

   sleep 1

   chattr -i /etc/resolv.conf >/dev/null 2>&1
   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo nameserver 9.9.9.9 | sudo tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} DNS Fixed${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not fix DNS${NC}"

   sleep 1

   chattr +i /etc/resolv.conf >/dev/null 2>&1

   while ! pgrep -x NetworkManager >/dev/null 2>&1; do
       NetworkManager >/dev/null 2>&1 && continue || break
   done && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Network Fixed${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not fix Network${NC}"

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} IPv6 enabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not enable IPv6${NC}"

   sudo nft flush ruleset >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Firewall was flushed${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not flush Firewall${NC}"

if ! pgrep -x tor >/dev/null 2>&1; then
   echo -e "\n${RED}[${GREEN}notice${RED}]${NC} neptune ${RED}stopped.${NC}"
   exit 0
else
   echo -e "\n${RED}[${NC}err${RED}]${NC} Could not stop neptune correctly${NC}"
   exit 1
fi

else
   echo -e "\n${RED}[${NC}err${RED}]${NC} Invalid Argument: ${RED}neptune is not running${NC}"
   exit 1
fi

}

# <-- Function Calls (arguments) --> #

while [ $# -gt 0 ]; do

case $1 in

start|--start|-start)

mode=1

# You cannot run this as an standard user #

if [ $EUID -ne 0 ]; then
        echo -e "\n${RED}[${NC}err${RED}] Run as root${NC}"
        exit 1
fi

torrc

if ! pgrep -x tor >/dev/null 2>&1; then
	echo -e "\n${BLUE}[${GREEN}notice${GREEN}]${LB} Starting ${P}Tor ${LB}and ${ORANGE}i2p${NC}"
    	config
    	exit 0
else
    	echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Invalid Argument: ${P}Tor ${GREEN}is running${NC}"
    	exit 0
fi

shift
break

;;

stop|--stop|-stop)

mode=2

# You cannot run this as an standard user #

if [ $EUID -ne 0 ]; then
        echo -e "\n${RED}[${WHITE}err${RED}] Run as root${NC}"
        exit 1
fi

stop

shift
break

;;

myip|--myip|-myip)

mode=3

myip

shift
break

;;

changeid|--changeid|-changeid)

mode=4

if pgrep -x tor >/dev/null 2>&1; then

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc $ADDR $CONTROL >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Got Newnym !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not get new id${NC}"

else

   echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Invalid Argument: ${P}Tor ${RED}is not running${NC}"
   exit 1

fi

shift

break

;;

enable|--enable|-enable)

mode=5

# You cannot run this as an standard user #

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}] Run as root${NC}"
    exit 1
fi

torrc

if [ -f /etc/systemd/system/neptune.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled neptune >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}] ${P}Tor ${GREEN}will start on boot${NC}"
    else
        systemctl enable neptune >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}was enabled${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not enable ${P}Tor${NC}"
    fi
fi

if [ -f /etc/sv/neptune/run ] && command -v runit >/dev/null 2>&1; then

        if [ -d /run/runit/service ]; then
            RSDIR=/run/runit/service
        elif [ -d /etc/service ]; then
              RSDIR=/etc/service
        elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
        fi

      if ls -l $RSDIR/neptune/ >/dev/null 2>&1; then
	      echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor${GREEN} will start on boot${NC}"
      else
           ln -s /etc/sv/neptune $RSDIR >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}] ${P}Tor ${GREEN} was enabled${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not enable ${P}Tor${NC}"
      fi
fi

if [ -f /etc/init.d/neptune ] && command -v rc-update >/dev/null 2>&1; then

      if sudo rc-update | grep -iE "neptune" >/dev/null 2>&1; then
           echo -e "\n${BLUE}[${GREEN}notice${BLUE}] ${P}Tor${GREEN} will start on boot${NC}"
      else
           sudo rc-update add neptune default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}was enabled${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not enable ${P}Tor${NC}"
      fi
fi

shift
break

;;

disable|--disable|-disable)

# You cannot run this as an standard user #

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}] Run as root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/neptune.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled neptune >/dev/null 2>&1; then
        echo -e "\n${RED}[${YELLOW}warn${RED}]${GREEN} neptune is disabled on this system${NC}"
        exit 0
    else

    systemctl disable neptune >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} neptune was disabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not disable neptune${NC}"
    exit 0
    fi
fi

if [ -f /etc/sv/neptune/run ] && command -v runit  >/dev/null 2>&1; then

      if [ -d /run/runit/service ]; then
          RSDIR=/run/runit/service

      elif [ -d /etc/service ]; then
              RSDIR=/etc/service

      elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
      fi

      if ! ls -l $RSDIR/neptune/ >/dev/null 2>&1; then
           echo -e "\n${RED}[${YELLOW}warn${RED}]${GREEN} neptune is disabled on this system${NC}"
           exit 0
      else

      rm -rf $RSDIR/neptune >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} neptune was disabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not disable neptune${NC}"
      exit 0
      fi
fi

if [ -f /etc/init.d/neptune ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "neptune" >/dev/null 2>&1; then
           echo -e "\n${RED}[${YELLOW}warn${RED}]${NC} neptune is disabled on this system${NC}"
           exit 0
      else

      rc-update del neptune default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} neptune was disabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Could not disable neptune${NC}"
      exit 0
      fi
fi

shift
break

;;

restart|--restart|-restart)

# You cannot run this as an standard user #

mode=7

if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}] Run as root${NC}"
    exit 1
fi

torrc

echo -e "\n${ORANGE}[${YELLOW}warn${ORANGE}]${BLUE} Restarting ${P}Tor ${LB}and ${ORANGE}i2p${NC}"

pkill -9 tor >/dev/null 2>&1
pkill -9 NetworkManager >/dev/null 2>&1

config

shift
break

;;

--help|-help|help)
mode=9

help

shift
break

;;

--*|-*|*)
mode=10

echo -e "\n${RED}[${NC}err${RED}] ${RED}unknown action ${YELLOW}'$1'${NC}, see ${GREEN}'neptune help'${NC}"

exit 1

shift
break

;;

esac
done

# Help page if ! mode = true
if [[ -z "$mode" ]]; then
    help
fi
