#!/bin/bash

###########################################################################################################################
#                                                                                                                         #
# 	Archnon-setup: Allows you to select many ways to install Archnon Linux, such as desktop, minimal, etc.                #
#                                                                                                                         #
#	Created by: archnon@protonmail.com # btw                                                                              #
#                                                                                                                         #
###########################################################################################################################
####################################################################
# Copyright (c) 2026 archnon@protonmail.com. All Rights Reserved.  #
####################################################################

##############
### colors ###
##############

WHITE="\e[1;37m"
GREEN="\e[1;32m"
RED="\e[1;31m"
LB="\e[1;36m"
BLUE="\e[1;34m"
YELLOW="\e[1;33m"
P="\e[1;35m"
ORANGE="\e[38;5;214m"
NC="\e[0m"

##############
### banner ###
##############

echo -e "                   ${LB}█████                                                                 █████"
echo -e "                  ${BLUE}▒▒${LB}███                                                                 ${BLUE}▒▒${LB}███"
echo -e "  ${LB}█████   ██████  ███████   █████ ████ ████████              ██████   ████████   ██████  ${BLUE}▒${LB}███████   ████████    ██████  ████████"
echo -e " ${LB}███${BLUE}▒▒   ${LB}███${BLUE}▒▒${LB}███${BLUE}▒▒▒${LB}███${BLUE}▒   ▒▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒▒${LB}███${BLUE}▒▒${LB}███ ██████████ ${BLUE}▒▒▒▒▒${LB}███ ${BLUE}▒▒${LB}███${BLUE}▒▒${LB}███ ███${BLUE}▒▒${LB}███ ${BLUE}▒${LB}███${BLUE}▒▒${LB}███ ${BLUE}▒▒${LB}███${BLUE}▒▒${LB}███  ███${BLUE}▒▒${LB}███${BLUE}▒▒${LB}███${BLUE}▒▒${LB}███"
echo -e "${BLUE}▒▒${LB}█████ ${BLUE}▒${LB}███████   ${BLUE}▒${LB}███     ${BLUE}▒${LB}███ ${BLUE}▒${LB}███  ${BLUE}▒${LB}███ ${BLUE}▒${LB}███${BLUE}▒▒▒▒▒▒▒▒▒▒   ${LB}███████  ${BLUE}▒${LB}███ ${BLUE}▒▒▒ ▒${LB}███ ${BLUE}▒▒▒  ▒${LB}███ ${BLUE}▒${LB}███  ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███"
echo -e " ${BLUE}▒▒▒▒${LB}███${BLUE}▒${LB}███${BLUE}▒▒▒    ▒${LB}███ ███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███  ${BLUE}▒${LB}███ ${BLUE}▒${LB}███            ███${BLUE}▒▒${LB}███  ${BLUE}▒${LB}███     ${BLUE}▒${LB}███  ███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███  ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███ ${BLUE}▒${LB}███"
echo -e " ${LB}██████ ${BLUE}▒▒${LB}██████   ${BLUE}▒▒${LB}█████  ${BLUE}▒▒${LB}████████ ${BLUE}▒${LB}███████            ${BLUE}▒▒${LB}████████ █████    ${BLUE}▒▒${LB}██████  ████ █████ ████ █████${BLUE}▒▒${LB}██████  ████ █████"
echo -e "${BLUE}▒▒▒▒▒▒   ${BLUE}▒▒▒▒▒▒     ▒▒▒▒▒    ▒▒▒▒▒▒▒▒  ▒${LB}███${BLUE}▒▒▒              ▒▒▒▒▒▒▒▒ ▒▒▒▒▒      ▒▒▒▒▒▒  ▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒ ▒▒▒▒▒  ▒▒▒▒▒▒  ▒▒▒▒ ▒▒▒▒▒"
echo -e "                                       ${BLUE}▒${LB}███"
echo -e "                                       ${LB}█████"
echo -e "                                      ${BLUE}▒▒▒▒▒"

echo -e "${P}╔════════════════════════╗
║ ${GREEN}ArchnonLinux ${WHITE}Installer ${P}║
╚════════════════════════╝${NC}"
echo -e "${WHITE}𝙳𝚎𝚟𝚎𝚕𝚘𝚙𝚎𝚍 𝚋𝚢:${P} 𝚊𝚛𝚌𝚑𝚗𝚘𝚗@𝚙𝚛𝚘𝚝𝚘𝚗𝚖𝚊𝚒𝚕.𝚌𝚘𝚖${NC}"

#############
### usage ###
#############

##### usage: setup-archnon <COMMAND> #####

usage() {
  echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}$0 ${BLUE}<${WHITE}COMMAND${BLUE}>${NC}"
  echo -e "\n${ORANGE}[${WHITE}1${ORANGE}]${P} --minimal${BLUE}|${P}-m: ${WHITE}Install the most basic version of ${GREEN}Archnon ${BLUE}(${LB}tty, shell, neptune${BLUE})${NC}"
  echo -e "\n${ORANGE}[${WHITE}2${ORANGE}]${P} --desktop${BLUE}|${P}-d: ${WHITE}Install ${GREEN}Archnon ${WHITE}with a desktop environment${NC}"
  echo -e "\n${ORANGE}[${WHITE}3${ORANGE}]${P} --help${BLUE}|${P}-h: ${WHITE}Prints this help page${NC}"
  exit 1
}

##### Instalation modes #####

while [ $# -gt 0 ]; do
  case $1 in

  -m | -minimal | --minimal)
    mode=1

    cmd=setup-alpine

    if ! $(command -v $cmd >/dev/null 2>&1); then
      echo -e "\n${RED}[${WHITE}X${RED}]${ORANGE} '$cmd' ${WHITE}command not found. Are you running ${LB}Alpine ${NC}Linux${WHITE}? ${NC}"
      exit 1
    fi

    if ! setup-alpine; then
      echo -e "\n${RED}[${WHITE}X${RED}] Hmm.. something was wrong, try as root${NC}"
      exit 1
    else
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Seems like there were no errors, done!${NC}"
      exit 0
    fi

    shift
    break
    ;;

  -d | -desktop | --desktop)
    mode=2

    cmd=setup-desktop

    if ! $(command -v $cmd >/dev/null 2>&1); then
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} '$cmd'${WHITE}, command not found. Are you running ${LB}Alpine ${NC}Linux${WHITE}?${NC}"
      exit 1
    fi

    if ! $cmd; then
      echo -e "\n${RED}[${WHITE}X${RED}]${WHITE} Hmm.. something was wrong, try as root${NC}"
      exit 1
    else
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Seems like there were no errors, done!${NC}"
      exit 0
    fi

    shift
    break
    ;;

  -h | -help | --help)
    mode=4
    usage

    shift
    break
    ;;

  --* | -* | *)
    mode=5
    echo -e "\n${RED}[${WHITE}X${RED}] Invalid option: ${ORANGE}'$1'${NC}"
    echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} Try: ${LB}'$0 ${BLUE}--help${LB}'${NC}"
    exit 1

    shift
    break
    ;;

  esac
done

##### Throw manual condition #####
if [[ -z $mode ]]; then
  usage
fi
