#!/bin/bash

###########################################################################################################################
#                                                                                                                         #
# 	Archnon-setup: Allows you to select many ways to install Archnon Linux, such as desktop, minimal, etc.                #
#                                                                                                                         #
#	Created by: archnon@protonmail.com # btw                                                                              #
#                                                                                                                         #
###########################################################################################################################

##############
### colors ###
##############

WHITE="\e[1;37m"
GREEN="\e[1;32m"
RED="\e[1;31m"
LB="\e[1;36m"
BLUE="\e[1;34m"
YELLOW="\e[1;33m"
P="\e[1;35m"
ORANGE="\e[38;5;214m"
NC="\e[0m"

#############
### usage ###
#############

##### usage: setup-archnon <COMMAND> #####

usage(){
	echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}$0 ${BLUE}<${WHITE}COMMAND${BLUE}>${NC}"
	echo -e "\n${ORANGE}[${WHITE}1${ORANGE}]${P} --minimal${BLUE}|${P}-m: ${WHITE}Install the most basic version of ${GREEN}Archnon ${BLUE}(${LB}tty, shell, neptune${BLUE})${NC}"
	echo -e "\n${ORANGE}[${WHITE}2${ORANGE}]${P} --desktop${BLUE}|${P}-d: ${WHITE}Install ${GREEN}Archnon ${WHITE}with a desktop environment${NC}"
	echo -e "\n${ORANGE}[${WHITE}3${ORANGE}]${P} --others${BLUE}|${P}-o: ${WHITE}Show an entire list of posible setups for${GREEN} Archnon${NC}"
	echo -e "\n${ORANGE}[${WHITE}4${ORANGE}]${P} --help${BLUE}|${P}-h: ${WHITE}Prints this help page${NC}"
	exit 1
}

##### Instalation modes #####

while [ $# -gt 0 ]; do
	case $1 in

	--minimal|-m)
	mode=1

	cmd=setup-alpine 	

	if ! $(command -v $cmd >/dev/null 2>&1); then
		echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} '$cmd' ${WHITE}command not found. Are you running ${LB}Alpine ${NC}Linux${WHITE}? ${NC}"
		exit 1
	fi

 	if ! setup-alpine; then
		echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Hmm.. something was wrong, try ${LB}'sudo $0 $1'${NC}"
		exit 1
	else
		echo -e "\n${GREEN}[${BLUE}notice${GREEN}]${LB} Seems like there were no errors, done!${NC}"
		exit 0
	fi
		
	shift
	break
	;;

	--desktop|-d)
	mode=2

	cmd=setup-desktop	

	if ! $(command -v $cmd >/dev/null 2>&1); then
		echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} '$cmd'${WHITE}, command not found. Are you running ${LB}Alpine ${NC}Linux${WHITE}?${NC}"
		exit 1
	fi

	if ! $cmd; then
		echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Hmm.. something was wrong, try ${LB}'sudo $0 $1'${NC}"
		exit 1
	else
		echo -e "\n${GREEN}[${BLUE}notice${GREEN}]${LB} Seems like there were no errors, done!${NC}"
		exit 0
	fi
	
	shift
	break
	;;

	--others|-o)
	mode=3

	ls --color=auto /usr/sbin | grep --color=auto "setup"

	shift
	break
	;;

	--help|-h)
	mode=4
	usage
	
	shift
	break
	;;

	--*|-*|*)
	mode=5
	echo -e "\n${RED}[${NC}err${RED}] Invalid option: ${YELLOW}'$1'${NC}"
    echo -e "\n$${RED}[${YELLOW}warn${RED}]${ORANGE} Try: ${LB}'$0 ${BLUE}--help${LB}'${NC}
    exit 1
	
	shift
	break
	;;

	esac
done

##### Throw manual condition #####
if [[ -z $mode ]]; then
	usage
fi
