#!/bin/bash

###########################################################################
#           System Wifi-Control - BY: archnon@protonmail.com            #
###########################################################################

###################################################################
# Copyright (c) 2026 archnon@protonmail.com. All Rights Reserved. #
###################################################################

### Colors (ignore this) ###

WHITE="\e[1;37m"

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

######################### banner #######################

echo -e "${GREEN}                  ███     ██████   ███            █████    ████ "
echo -e "${GREEN}                 ▒▒▒     ███▒▒███ ▒▒▒            ▒▒███    ▒▒███ "
echo -e "${GREEN} █████ ███ █████ ████   ▒███ ▒▒▒  ████   ██████  ███████   ▒███ "
echo -e "${GREEN}▒▒███ ▒███▒▒███ ▒▒███  ███████   ▒▒███  ███▒▒███▒▒▒███▒    ▒███ "
echo -e "${GREEN} ▒███ ▒███ ▒███  ▒███ ▒▒▒███▒     ▒███ ▒███ ▒▒▒   ▒███     ▒███ "
echo -e "${GREEN} ▒▒███████████   ▒███   ▒███      ▒███ ▒███  ███  ▒███ ███ ▒███ "
echo -e "${GREEN}  ▒▒████▒████    █████  █████     █████▒▒██████   ▒▒█████  █████"
echo -e "${GREEN}   ▒▒▒▒ ▒▒▒▒    ▒▒▒▒▒  ▒▒▒▒▒     ▒▒▒▒▒  ▒▒▒▒▒▒     ▒▒▒▒▒  ▒▒▒▒▒ "
echo -e "${GREEN}                                                                "
echo -e "${GREEN}                                                                "
echo -e "${GREEN}                                                                "

echo -e "${BLUE}╔═════════════════════════════╗
║ ${WHITE}Connect system to wifi tool${BLUE} ║
╚═════════════════════════════╝${NC}"
echo -e "${WHITE}𝙳𝚎𝚟𝚎𝚕𝚘𝚙𝚎𝚍 𝚋𝚢:${P} 𝚊𝚛𝚌𝚑𝚗𝚘𝚗@𝚙𝚛𝚘𝚝𝚘𝚗𝚖𝚊𝚒𝚕.𝚌𝚘𝚖${NC}"

#<- Check if networkmanager's cli util is installed ->#

if ! $(command -v nmcli >/dev/null 2>&1); then
  echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'networkmanager, networkmanager-cli'${NC}"
  exit 1
fi

# <- Start Network daemon if not running ->

if ! pgrep -x NetworkManager >/dev/null 2>&1; then
  NetworkManager >/dev/null 2>&1
fi

# <- Manual -> #

help_p() {
  echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${GREEN}$0 ${YELLOW}<${NC}COMMAND${YELLOW}> <${NC}OPTIONS${YELLOW}>${NC}"
  echo -e "\n${BLUE}[${LB}1${BLUE}]${LB} --connect${BLUE}|${LB}-c: ${YELLOW}<${NC}ssid${YELLOW}> <${NC}passwd${YELLOW}> <${NC}ifname${YELLOW}>${NC}"
  echo -e "\n${BLUE}[${LB}2${BLUE}]${LB} --delete-connection${BLUE}|${LB}-d: ${YELLOW}<${NC}label${YELLOW}>${NC}"
  echo -e "\n${BLUE}[${LB}3${BLUE}]${LB} --list-all${BLUE}|${LB}-l: ${YELLOW}<${NC}object${YELLOW}> ${BLUE}(${LB}--established/--access-point${BLUE})${NC}"
  echo -e "\n${BLUE}[${LB}4${BLUE}]${LB} --help${BLUE}|${LB}-help${BLUE}|${LB}help${BLUE}|${LB}-h:${WHITE} print usage${NC}"
}

# <- Arguments Section ->

while [ $# -gt 0 ]; do
  case $1 in
  --connect | -c)
    mode=1

    ssid=$2
    passwd=$3
    ifname=$4

    if [[ -z $ssid || -z $passwd || -z $ifname ]]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing args${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}$0 ${BLUE}--connect ${YELLOW}<${P}ssid${YELLOW}> <${P}passwd${YELLOW}> <${P}ifname${YELLOW}>${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} example: ${LB}$0 ${BLUE}--connect ${YELLOW}my_home1 ${YELLOW}password123 ${YELLOW}wlan0${NC}"
      exit 1
    else
      nmcli dev wifi rescan >/dev/null 2>&1
      nmcli dev wifi connect $ssid password $passwd ifname $ifname >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${LB} Connect to: ${ORANGE}'$ssid'${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Connect to: ${ORANGE}'$ssid'${NC}"
      exit 0
    fi

    shift
    break
    ;;

  --delete-connection | -d)
    mode=2

    connection=$2

    if [[ -z $connection ]]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing label${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}$0 ${BLUE}--delete-connection ${YELLOW}<${P}connection${YELLOW}>${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} example: ${LB}$0 ${BLUE}--delete-connection ${YELLOW}my_home1${NC}"
      exit 1
    else
      nmcli connection delete $connection >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Delete: ${ORANGE}'$connection'${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Delete: ${ORANGE}'$connection'${NC}"
      exit 0
    fi

    shift
    break
    ;;

  --list-all | -l)
    mode=3

    target=$2

    if [[ -z $target ]]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing object${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}$0 ${BLUE}--list-all ${YELLOW}<${P}object${YELLOW}>${NC}"
      exit 1
    fi

    if [[ $target == "--established" ]]; then
      nmcli connection
      exit 0
    elif [[ $target == "--access-point" ]]; then
      if nmcli dev wifi rescan >/dev/null 2>&1; then
        sleep 1
        nmcli dev wifi
      else
        echo -e "\n${RED}[${WHITE}X${RED}] No wifi devices${NC}"
        exit 1
      fi
    else
      echo -e "\n${RED}[${WHITE}X${RED}] Invalid object: ${ORANGE}'$target'${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}] Objects are: ${NC}"
      echo -e "\n${BLUE}--established: ${WHITE}show existing connections with APs${NC}"
      echo -e "\n${BLUE}--access-point: ${WHITE}shows available Access Points to connect${NC}"
      exit 1
    fi

    shift
    break
    ;;

  --help | -help | help | -h)
    mode=4

    help_p

    shift
    break
    ;;

  --* | -* | *)
    mode=5

    help_p

    shift
    break
    ;;
  esac
done

if [ -z "$mode" ]; then
  help_p
  exit 0
fi
