#!/bin/bash

###########################################################################
#           System Wifi-Control - BY: archnon@protonmail.com           #  
###########################################################################

### Colors (ignore this) ###

WHITE="\e[1;37m"

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

#<- Check if networkmanager's cli util is installed ->#

if ! $(command -v nmcli >/dev/null 2>&1); then
    echo -e "\n${RED}[${WHITE}err${RED}] ${ORANGE}'nmcli':${WHITE} command not found, please, install ${LB}'networkmanager-cli'${WHITE} from your package manager!${NC}"
    exit 1
fi

# <- Start Network daemon if not running ->

if ! pgrep -x NetworkManager >/dev/null 2>&1; then
	NetworkManager >/dev/null 2>&1
fi

# <- Manual -> #

help_p(){
	echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${WHITE} usage: ${GREEN}$0 ${YELLOW}<${NC}option${YELLOW}> <${NC}args${YELLOW}>${NC}"
	echo -e "\n${BLUE}[${GREEN}1${BLUE}]${LB} --connect${BLUE}|${LB}-c: ${YELLOW}<${NC}ssid${YELLOW}> <${NC}passwd${YELLOW}> <${NC}ifname${YELLOW}>${NC}"
	echo -e "\n${BLUE}[${GREEN}2${BLUE}]${LB} --delete-connection${BLUE}|${LB}-d: ${YELLOW}<${NC}conection_name${YELLOW}>${NC}"
	echo -e "\n${BLUE}[${GREEN}3${BLUE}]${LB} --list-all${BLUE}|${LB}-l: ${YELLOW}<${NC}object${YELLOW}> ${BLUE}(${LB}wifi/created${BLUE})${NC}"
	echo -e "\n${BLUE}[${GREEN}4${BLUE}]${LB} --help${BLUE}|${LB}-help${BLUE}|${LB}help${BLUE}|${LB}-h:${WHITE} Print manual${NC}"
}

# <- Arguments Section ->

while [ $# -gt 0 ]; do
	case $1 in
	--connect|-c)
	mode=1

	ssid=$2
	passwd=$3
	ifname=$4
	
	if [[ -z $ssid || -z $passwd || -z $ifname ]]; then
	    echo -e "\n${RED}[${WHITE}err${RED}] Missing args${NC}"
	    echo -e "\n${LB}[${YELLOW}warn${LB}]${WHITE} usage: ${GREEN}$0 ${NC}--connect ${YELLOW}<${NC}ssid${YELLOW}> <${NC}passwd${YELLOW}> <${NC}ifname${YELLOW}>${NC}"
	    echo -e "\n${LB}[${YELLOW}warn${LB}]${WHITE} Example: ${GREEN}$0 ${YELLOW}my_home1 ${ORANGE}password123 ${YELLOW}wlan0${NC}"
	    exit 1
	else
	    nmcli dev wifi rescan >/dev/null 2>&1
	    nmcli dev wifi connect $ssid password $passwd ifname $ifname >/dev/null 2>&1 && echo -e "\n${GREEN}[${WHITE}notice${GREEN}]${ORANGE} $ssid${NC}: ${GREEN}connected${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not connect to ${BLUE}'$ssid'${WHITE}, using ${ORANGE}'$ifname'${WHITE}${NC}"
	    exit 0
	fi

	
	shift
	break
	;;

	--delete-connection|-d)
	mode=2

	connection=$2

	if [[ -z $connection ]]; then
	    echo -e "\n${RED}[${WHITE}err${RED}] Missing connection name${NC}"
	    echo -e "\n${P}[${YELLOW}warn${P}]${WHITE} usage: ${GREEN}$0 ${ORANGE}--delete-connection ${YELLOW}<${NC}connection${YELLOW}>${NC}"
	    exit 1
	else
	    nmcli connection delete $connection >/dev/null 2>&1 && echo -e "\n${GREEN}[${WHITE}notice${GREEN}] ${ORANGE}$connection${RED}: deleted${NC}" || echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Could not delete: ${ORANGE}'$connection'${NC}"
	    exit 0
	fi

		
	shift
	break
	;;

	--list-all|-l)
	mode=3

	target=$2
	
	if [[ -z $target ]]; then
		echo -e "\n${RED}[${WHITE}err${RED}] Missing object${NC}"
		echo -e "\n${P}[${YELLOW}warn${P}]${WHITE} usage: ${GREEN}$0 ${YELLOW}--list-all ${ORANGE}<${NC}object${ORANGE}>${NC}"
		exit 1
	fi
	
	if [[ $target == "--established" ]]; then
		nmcli connection
		exit 0
	elif [[ $target == "--access-point" ]]; then
		if nmcli dev wifi rescan >/dev/null 2>&1; then
		   sleep 1
		   nmcli dev wifi
		else
		   echo -e "\n${RED}[${WHITE}err${RED}] There are no wifi devices${NC}"
		   exit 1
		fi
	else
		echo -e "\n${RED}[${WHITE}err${RED}]${WHITE} Invalid object ${ORANGE}'$target'${NC}"
		echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${WHITE} Objects are: ${NC}"
		echo -e "\n${LB}--established: ${WHITE}Show existing connections with APs${NC}"
		echo -e "\n${LB}--access-point: ${WHITE}Shows available Access Points to connect${NC}"
		exit 1
	fi


	shift 
	break
	;;
	
	--help|-help|help|-h)
	mode=4

	help_p

	shift
	break
	;;

	--*|-*|*)
	mode=5

	help_p
	
	shift
	break
	;;
	esac
done

if [ -z "$mode" ]; then
	help_p
	exit 0
fi
